name: CI

on: 
    pull_request:
        branches:
        - main

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go 1.22
              uses: actions/setup-go@v5
              with:
                go-version: "1.22"

            - name: build
              run: |
                cd ./src/productcatalogservice
                go mod download
                go build -o product-catalog-service

            - name: test
              run: |
                cd ./src/productcatalogservice
                go test ./...
